Done
Leila-2/nodejs-hw-rest-api pull request #2
Opened 2022-02-04 00:19 UTC by Leila-2

Привет!)
Сделала 3ю домашку)

2022-02-04 19:57 UTC, KirillKulakow commented on routes/api/contacts.js
>  /* eslint-disable new-cap */
почему выключила?)
рекомендация - если ты знаешь что это и тебе оно не нужно - пиши в конфигурации ESLint 
я подозреваю ошибка светилась здесь: `const router = express.Router()`
так почему не сделать например так:
```
3 строка const { Router } = require('express')
8 строка const router = new Router()
```

2022-02-04 20:00 UTC, KirillKulakow commented on routes/api/contacts.js
> +    if (error.message.includes("Cast to ObjectId failed")) {
рекомендация
лучше делать проверку перед тем как делать запрос в бд и потом отлавливать ошибку
есть хороший метод mongoose.Types.ObjectId.isValid

2022-02-04 20:01 UTC, KirillKulakow commented on routes/api/contacts.js
> +      error.status = 400;
зачем перезаписывать статус если ты его ставишь выполнением функции в строке 44
тоесть ты меняешь статус с 400 на 400

2022-02-04 20:01 UTC, KirillKulakow commented on routes/api/contacts.js
>      const { contactId } = req.params;
нет проверки валидности ид

2022-02-04 20:01 UTC, KirillKulakow commented on routes/api/contacts.js
>      const { contactId } = req.params
нет проверки валидности ид

2022-02-04 20:01 UTC, KirillKulakow commented on routes/api/contacts.js
> +    const { contactId } = req.params
нет проверки валидности ид

2022-02-04 20:02 UTC, KirillKulakow requested changes
Need fix

2022-02-06 10:07 UTC, Leila-2 commented on routes/api/contacts.js
>  /* eslint-disable new-cap */
Оуу, хорошо), я просто не знала ка правильно это исправить, а в настройки линтеров лезть побоялась

2022-02-06 10:09 UTC, Leila-2 commented on routes/api/contacts.js
> +    if (error.message.includes("Cast to ObjectId failed")) {
Можете показать на примере, я не совсем понимаю как отловить ошибку до запроса на бд, точнее не могу представить как это должно выглядеть(

2022-02-06 10:10 UTC, Leila-2 commented on routes/api/contacts.js
> +      error.status = 400;
Да, я поняла :/

2022-02-06 10:13 UTC, KirillKulakow commented on routes/api/contacts.js
> +    if (error.message.includes("Cast to ObjectId failed")) {
```
if (!mongoose.Types.ObjectId.isValid(id)) { badRequestError }
const result = await Contact.findById(contactId);
```

2022-02-13 15:19 UTC, KirillKulakow commented on routes/api/contacts.js
> +    if (error.message.includes("Cast to ObjectId failed")) {
зачем тебе этот if - если эта ошибка никогда не произойдет?

2022-02-13 15:22 UTC, KirillKulakow approved these changes

2022-02-14 13:38 UTC, merged